packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of apps/
  - 'apps/**'
  - docs

catalog:
  '@arcgis/core': ^4.32.10
  '@vueuse/core': 11.3.0
  "@vitejs/plugin-vue": 5.2.3
  vite: 6.3.3
  "vite-plugin-external": 6.2.1
  "vite-plugin-html": ^3.2.2
  "vite-plugin-vuetify": ^2.1.1
  lodash-es: ^4.17.21
  pinia: ^3.0.2
  vue: 3.5.13
  vue-router: ^4.5.1
  sass: ^1.79.5
  "sass-loader": ^16.0.1
