packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of apps/
  - 'apps/**'
  - docs

catalog:
  '@arcgis/core': ^4.31.3
  '@vueuse/core': 11.3.0
  "@vitejs/plugin-vue": 5.1.4
  vite: 5.4.10
  "vite-plugin-external": ^4.3.1
  "vite-plugin-html": ^3.2.2
  "vite-plugin-vuetify": ^2.0.4
  lodash-es: ^4.17.21
  pinia: ^2.1.7
  vue: 3.5.13
  vue-router: ^4.3.3
  sass: ^1.79.5
  "sass-loader": ^16.0.1
