packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of apps/
  - 'apps/**'
  - docs

catalog:
  '@arcgis/core': ^4.31.3
  '@vueuse/core': ^9.9.0
  vite: 5.4.10
  pinia: ^2.1.7
  vue: ^3.4.29
  vue-router: ^4.3.3
  sass: ^1.79.5
